### ISSUE TITLE
Influence of data preprocessing on model performance

### ISSUE THREAD

**Issue by jfzhang52** [xiyang1012/Local-Crowd-Counting#12]
Hi, thanks for your excellent work and the open-source codes! 
I'm very interested in the novel optimization criterion proposed in your paper and tried to reproduce it locally. But there is a confusing problem of performance degradation when I restrained the height and width of the test images to make sure that they are divisible by a particular number (like, 8, 16, or 32). This data preprocessing strategy is inspired by [C^3 Framework](https://arxiv.org/abs/1907.02724) and guarantees the output size of some down-sampling layers count meet the requirements of subsequent processing. More details of the test results are shown in the table below.

|           | pretrained | resize | MAE   | MSE    |
| --------- | ---------- | ------ | ----- | ------ |
| Reported  | ✔️          |        | 59.68 | 95.72  |
| Reproduce | ✔️          | ✔️      | 62.47 | 101.98 |

This issue is to sincerely ask you how such a simple operation can have such an obvious impact on the experimental results.

**Comment by xiyang1012** [comment]
Hi, thanks for your attention to this work!
In fact, both the training and test images are resized to be divisible by 64. So I think that's not the main reason for performance degradation. The codes may be different from the latest version of C3F in some details. You could focus on the differences and try again. Some model parameters, such as "patchmax", also need to be set reasonably. For the best result, you could also try to modify the batch size or increase the training epoch.

**Comment by jfzhang52** [comment]
Thanks a lot for your prompt reply, maybe I should modify the codes and run more experiments to figure out what went wrong.
